# =============================================================================
#  Extended_Model_Population.r
#  Population (virtual-individual) version of Extended_Model.r.
#
#  Extended_Model.r's .create.params() builds organ volumes (V*) and plasma
#  flows (Q*) from fixed literature fractions of a single point-estimate BW.
#  This script replaces that physiology block with per-individual organ mass
#  and blood flow generated by the PopGen algorithm (popgen_consts.R /
#  popgen_port.R), so the model is solved once per virtual individual instead
#  of once for a population-average body.
#
#  Mapping notes (see .map_popgen_individual() below for the exact code):
#   - Organ mass (kg) -> organ volume (L): popgen only generates organ MASS,
#     so volume is computed as V = M / density using standard per-organ
#     tissue densities (Brown et al. 1997; ICRP Publication 89), not by
#     treating mass as volume directly (an earlier version of this script
#     assumed unit density for every organ, which is the "V(organ) used to
#     be M(organ)" inconsistency this fixes). MK/ML/VPTC downstream use the
#     popgen organ mass directly rather than re-deriving mass from volume.
#   - Organ blood flow (popgen, L/h) -> plasma flow (model's Q*, L/time_scale):
#     multiplied by inv_time_scale (hours per time_scale unit) and by
#     (1 - Htc), exactly mirroring how Extended_Model.r derives its own QC
#     (QC <- QCC * BW^0.75 * (1 - Htc)) from a blood-flow-basis literature
#     constant.
#   - PopGen has no "rest of body" organ; its Bone compartment is the largest
#     tissue with no dedicated compartment in Extended_Model.r, so Bone
#     mass/flow is mapped onto the model's rest-of-body compartment (VR/QR),
#     per explicit request.
#   - Lung: popgen's own "Lung_flow" column is a cardiac-output placeholder,
#     not real lung-tissue perfusion (see popgen_port.R's header on
#     Lung_Bronchial_flow). The model's QLun is mapped from
#     Lung_Bronchial_flow (the actual pulmonary-tissue/bronchial perfusion),
#     matching the convention popgen_r_as_population() already uses elsewhere
#     in this project.
#   - GI tract: Extended_Model.r has a single lumped GI compartment, so
#     popgen's Stomach + Small intestine + Large intestine are used via
#     popgen_r()'s own GI_tract_mass_kg / GI_tract_flow (lump_GI = TRUE).
#   - Liver flow (QL) is mapped from popgen's "Liver_flow" only (the hepatic
#     ARTERY contribution) -- exactly as in Extended_Model.r, where portal
#     inflow from GI/Spleen/Pancreas is already handled separately inside
#     .ode.func()'s liver mass-balance equation. Do not use Liver_Total_flow
#     here, it would double-count the portal contribution.
#   - QC is defined as the sum of the mapped organ Q's (not popgen's own
#     `cardiac_output` field, which excludes the small lung-bronchial term)
#     so the plasma-flow balance (QBAL) is exact by construction.
#   - Chemical-specific PK parameters (Vmax, Km, RAF, partition coefficients,
#     rate constants) and the administered dose are NOT generated by popgen
#     and are therefore identical across individuals, exactly as in
#     Extended_Model.r; only physiology (organ mass/flow, and hence BW) varies
#     across the population.
#   - Hematocrit (Htc, .sample_Htc()): popgen does not generate it, and
#     Extended_Model.r uses one fixed Htc = 0.42 for everyone. Here each
#     individual instead draws its own Htc from a sex-specific truncated
#     normal (mean/sd backed out of standard ~41-51% male / ~36-46% female
#     clinical reference intervals), so plasma-basis flows/partition
#     coefficients (both scaled by (1 - Htc)) vary accordingly. Water
#     consumption remains the same fixed literature constant Extended_Model.r
#     uses; popgen does not generate that either.
#   - GFR (.gfr_age_factor()): GFRC (24.19 L/h/kg kidney, Corley 2005) is a
#     single filtration-rate-per-kidney-mass constant with no age dependence;
#     GFR = GFRC * VK alone assumes filtration efficiency per gram of kidney
#     tissue is the same at every age, when in reality it declines with age
#     (nephron loss/glomerulosclerosis) independent of gross kidney mass. A
#     literature-based relative age-decline factor (Davies & Shock 1950;
#     Lindeman et al. 1985 BLSA: ~0.5-0.7%/year of peak GFR after the ~30s
#     plateau) is applied on top of GFRC*VK. The factor is per-sex but both
#     sexes currently share the same slope -- the ~140 vs 120 mL/min/1.73m^2
#     male/female BASELINE gap in that literature is mostly a body/kidney-size
#     effect already captured by popgen's sex-specific VK, so it is
#     deliberately NOT applied a second time as a baseline multiplier here
#     (that would double-count the size-driven share of the sex gap).
#
#  Dependencies: popgen_consts.R and popgen_port.R must be in the working
#  directory (same convention Run_extended.r uses for Extended_Model.r).
# =============================================================================

library(deSolve)
library(tidyverse)

#=========================
# 0. PopGen dependencies
#=========================
if (!exists("POPGEN_CONSTS")) {
  if (file.exists("popgen_consts.R")) source("popgen_consts.R") else
    stop("Extended_Model_Population.r requires popgen_consts.R -- source() it first, or run from the folder containing it")
}
if (!exists("popgen_r")) {
  if (file.exists("popgen_port.R")) source("popgen_port.R") else
    stop("Extended_Model_Population.r requires popgen_port.R -- source() it first, or run from the folder containing it")
}

#=========================
# 1. Chemical-specific parameters (identical to Extended_Model.r)
#=========================
#'
#' @keywords internal
#'
.get_chemical_vars <- function(chemical) {

  variables <- read.csv("estimated_parameters.csv", row.names = 1) %>% select(all_of(chemical))

  PC <- data.frame(
    DONA = c(0.124947389, 0.093417353, 0.453895406, 0.39404558, 0.516525519, 0.260245376, 0.802893425, 0.245729715, 0.333327203, 0.554155414),
    HFPO_DA = c(0.132911327, 0.167241461, 0.335472967, 0.300497404, 0.363279275, 0.993256185, 0.642857005, 0.350626131, 0.297788612, 0.405961151),
    PFBA = c(0.129165456, 0.127429659, 0.278016846, 0.126434927, 0.325021589, 0.361492503, 0.603411764, 0.156031705, 0.304498056, 0.378143683),
    PFBS = c(0.197947634, 0.350683638, 0.429465629, 0.408625829, 0.450282602, 0.458664426, 0.673479649, 0.220412593, 0.409674109, 0.478156735),
    PFDA = c(0.050113807, 0.497299996, 0.89483373, 0.018004527, 0.073924732, 3.409634891, 0.040734602, 0.02085036, 0.094637375, 0.840556154),
    PFHpA = c(0.098067143, 0.054941827, 0.527979623, 0.231463023, 0.583097047, 1.168406124, 0.841703023, 0.279995413, 0.39715958, 0.623833077),
    PFHxA = c(0.145771589, 0.054376066, 0.485393186, 0.213538328, 0.543916041, 0.263938131, 0.814340373, 0.260989886, 0.390107977, 0.59141182),
    PFHxS = c(0.254116384, 0.053076379, 0.430516787, 0.378514537, 0.504146317, 0.244750669, 0.079558592, 0.118922026, 0.318553055, 0.529997757),
    PFNA = c(0.136107702, 0.166395692, 0.662236244, 0.655397113, 0.064056921, 2.566865548, 1.487738844, 0.016102782, 0.666595171, 0.02198743),
    PFOA = c(0.063812225, 0.158920559, 0.406905162, 0.11934646, 0.460418226, 1.261933405, 0.188237566, 0.109461608, 0.172308549, 0.985281684),
    PFOS = c(0.311979033, 0.311341927, 0.560484488, 1.131641191, 1.02340325, 1.071556994, 0.239982717, 0.104992399, 1.18549103, 1.05033605)
  ) %>% select(all_of(chemical))

  rownames(PC) <- c("Adipose", "Brain", "Gonads", "Gut", "Heart", "Liver",
                     "Lung", "Muscle", "Skin", "Spleen")

  list(variables = variables, PC = PC)
}

#=========================
# 2. Required-input validation
#=========================
#'
#' @keywords internal
#'
.required_population_fields <- c("n", "dataset", "age_range", "bmi_range", "height_range",
                                  "prob_male", "ethnicity_probs", "population_type")

#'
#' @keywords internal
#'
.check_required <- function(user_input, fields) {
  missing_fields <- fields[!vapply(fields, function(f) {
    f %in% names(user_input) && !is.null(user_input[[f]]) && !(length(user_input[[f]]) == 1 && is.na(user_input[[f]]))
  }, logical(1))]
  if (length(missing_fields) > 0) {
    stop("Missing required input parameter(s): ", paste(missing_fields, collapse = ", "))
  }
}

#=========================
# 3. Population generation (organ mass & flow source)
#=========================
#' Generate the virtual population underlying this simulation
#'
#' Thin, validated wrapper around popgen_r() (popgen_port.R). All population
#' parameters below are REQUIRED in `user_input` -- there is no silent
#' default, since these are exactly the parameters that determine every
#' individual's organ mass and blood flow.
#'
#' @param user_input List that must contain:
#'   \item{n}{population size (accepted individuals)}
#'   \item{dataset}{"ICRP" or "P3M"}
#'   \item{age_range}{c(lower, upper) years}
#'   \item{bmi_range}{c(lower, upper) kg/m2}
#'   \item{height_range}{c(lower, upper) cm}
#'   \item{prob_male}{probability an individual is male}
#'   \item{ethnicity_probs}{c(White, Black, NonBlackHispanic); must sum <= 1}
#'   \item{population_type}{"Realistic" or "HighVariation"}
#'   May optionally contain `seed` (RNG seed; NULL if omitted).
#' @return list(pop = data.frame, n_discarded = integer), as returned by popgen_r()
#' @export
#'
.generate_population <- function(user_input) {
  .check_required(user_input, .required_population_fields)

  popgen_r(
    n = user_input$n,
    dataset = user_input$dataset,
    age_range = user_input$age_range,
    bmi_range = user_input$bmi_range,
    height_range = user_input$height_range,
    prob_male = user_input$prob_male,
    ethnicity_probs = user_input$ethnicity_probs,
    population_type = user_input$population_type,
    flow_units = "LitresPerHour",
    seed = if (is.null(user_input$seed)) NULL else user_input$seed,
    lump_GI = TRUE
  )
}

#=========================
# 4. Map one individual's popgen organ mass/flow onto the PBK compartments
#=========================
#' Map a single popgen individual onto Extended_Model.r's compartments
#'
#' @param ind One row of the data.frame returned by .generate_population()$pop
#'   (as produced by popgen_r(), with lump_GI = TRUE, flow_units = "LitresPerHour").
#' @param Htc Hematocrit fraction (fixed literature constant; popgen does not
#'   generate it).
#' @param inv_time_scale Hours per model time-scale unit (as computed by
#'   Extended_Model.r's .create.params(), e.g. 24 for "days").
#' @return list of BW plus every V*/Q* Extended_Model.r's ODE system needs.
#' @keywords internal
#'
.map_popgen_individual <- function(ind, Htc, inv_time_scale) {

  BW <- ind[["body_mass_kg"]]

  # --- Tissue densities (kg/L, equivalently g/mL): standard PBPK literature
  # values (Brown et al. 1997; ICRP Publication 89). Popgen supplies organ
  # MASS (kg), not volume -- treating mass as volume directly (implicit
  # density = 1 for every organ) was the unit inconsistency being fixed here;
  # volume is now computed as V = M / density per organ. Gonads and Pancreas
  # are not separately tabulated in Brown 1997, so they use the generic
  # soft-tissue value (same as Kidney/Liver/Muscle); verify against your
  # preferred source if you need more precision than these round literature
  # values.
  dens <- c(Adipose = 0.92, Brain = 1.04, Gonads = 1.05, Heart = 1.03,
            Lung = 1.05, Muscle = 1.04, Skin = 1.10, Spleen = 1.06,
            Pancreas = 1.05, GI = 1.04, Liver = 1.05, Kidney = 1.05, Bone = 1.30)

  # --- Tissue masses (kg), straight from popgen ---
  MAdi <- ind[["Adipose_mass_kg"]]
  MBra <- ind[["Brain_mass_kg"]]
  MGon <- ind[["Gonads_mass_kg"]]
  MHea <- ind[["Heart_mass_kg"]]
  MLun <- ind[["Lung_mass_kg"]]
  MMus <- ind[["Muscle_mass_kg"]]
  MSki <- ind[["Skin_mass_kg"]]
  MSpl <- ind[["Spleen_mass_kg"]]
  MPan <- ind[["Pancreas_mass_kg"]]
  MGI  <- ind[["GI_tract_mass_kg"]]   # lumped Stomach + Small intestine + Large intestine
  MLiv <- ind[["Liver_mass_kg"]]
  MKid <- ind[["Kidneys_mass_kg"]]
  MR <- ind[["Bone_mass_kg"]]      # Bone -> rest of body (no dedicated bone compartment in the model)

  # --- Tissue volumes (L): V = M / density ---
  VAdi <- MAdi / dens[["Adipose"]]
  VBra <- MBra / dens[["Brain"]]
  VGon <- MGon / dens[["Gonads"]]
  VHea <- MHea / dens[["Heart"]]
  VLun <- MLun / dens[["Lung"]]
  VMus <- MMus / dens[["Muscle"]]
  VSki <- MSki / dens[["Skin"]]
  VSpl <- MSpl / dens[["Spleen"]]
  VPan <- MPan / dens[["Pancreas"]]
  VGI  <- MGI  / dens[["GI"]]
  VL   <- MLiv / dens[["Liver"]]
  VK   <- MKid / dens[["Kidney"]]
  VR   <- MR / dens[["Bone"]]

  # --- Tissue plasma flows (L/time_scale): popgen flow (L/h, blood basis) ->
  # model flow (L/time_scale, plasma basis), mirroring how Extended_Model.r's
  # own QC <- QCC * BW^0.75 * (1 - Htc) converts a blood-flow-basis literature
  # constant into a plasma flow ---
  to_model_Q <- function(Lph) Lph * inv_time_scale * (1 - Htc)

  QAdi <- to_model_Q(ind[["Adipose_flow"]])
  QBra <- to_model_Q(ind[["Brain_flow"]])
  QGon <- to_model_Q(ind[["Gonads_flow"]])
  QHea <- to_model_Q(ind[["Heart_flow"]])
  QLun <- to_model_Q(ind[["Lung_Bronchial_flow"]])  # actual lung-tissue perfusion; Lung_flow itself is a CO placeholder, not tissue flow
  QMus <- to_model_Q(ind[["Muscle_flow"]])
  QSki <- to_model_Q(ind[["Skin_flow"]])
  QSpl <- to_model_Q(ind[["Spleen_flow"]])
  QPan <- to_model_Q(ind[["Pancreas_flow"]])
  QGI  <- to_model_Q(ind[["GI_tract_flow"]])
  QL   <- to_model_Q(ind[["Liver_flow"]])   # hepatic ARTERY only; portal inflow from GI/Spleen/Pancreas is handled inside .ode.func()'s liver balance
  QK   <- to_model_Q(ind[["Kidneys_flow"]])
  QR   <- to_model_Q(ind[["Bone_flow"]])    # Bone -> rest of body


  QC <- QK + QL + QR + QAdi + QBra + QGon + QHea + QLun + QMus + QSki + QSpl + QPan + QGI

 MBal <- BW - (MR + MLiv + MKid + MAdi + MBra + MGon + MHea + MLun + MMus + MSki + MSpl + MPan + MGI) 
  list(
    BW = BW,
    QC = QC, QK = QK, QL = QL, QR = QR, QAdi = QAdi, QBra = QBra, QGon = QGon,
    QHea = QHea, QLun = QLun, QMus = QMus, QSki = QSki, QSpl = QSpl, QPan = QPan, QGI = QGI,
    VAdi = VAdi, VBra = VBra, VGon = VGon, VHea = VHea, VLun = VLun, VMus = VMus,
    VSki = VSki, VSpl = VSpl, VPan = VPan, VGI = VGI, VL = VL, VK = VK, VR = VR,
    MLiv = MLiv, MKid = MKid  # organ mass (kg), straight from popgen; used downstream for ML/MK/VPTC instead of re-deriving mass from volume with a second, possibly-inconsistent density
  )
}

#' Age-related correction factor for GFR, on top of GFRC * VK
#'
#' GFRC (Corley 2005) is a single filtration-rate-per-kidney-mass constant;
#' this factor layers in the well-documented decline of GFR per gram of
#' kidney tissue with age (nephron loss/glomerulosclerosis), which anatomical
#' kidney-mass scaling (VK) alone does not capture. Normalized to 1.0 at
#' `age_ref` (the literature plateau, ~30s), linearly declining by
#' `decline_per_year[sex]` fraction of peak per year thereafter, floored at
#' `f_min` to keep the correction physiologically plausible (not <=0) for
#' very old ages.
#'
#' `decline_per_year` is a per-sex named vector so the two sexes' decline
#' RATES can be tuned independently if future evidence supports it; both
#' currently share the same ~0.6%/year slope (midpoint of Davies & Shock
#' 1950's ~8 mL/min/1.73m^2 per decade off a 140 mL/min/1.73m^2 peak, and
#' Lindeman et al. 1985's ~0.75 mL/min/year off the same peak). The
#' male/female BASELINE GFR gap reported in that literature (~140 vs
#' ~120 mL/min/1.73m^2) is intentionally NOT reproduced here as a second,
#' separate multiplier -- it is predominantly a body/kidney-size effect
#' already carried by popgen's sex-specific VK (see .map_popgen_individual()
#' and the file header), and applying it again here would double-count it.
#'
#' @keywords internal
#'
.gfr_age_factor <- function(age, sex, age_ref = 30,
                             decline_per_year = c(Male = 0.006, Female = 0.006),
                             f_min = 0.3) {
  rate <- decline_per_year[[sex]]
  pmax(f_min, 1 - rate * pmax(0, age - age_ref))
}

#' Random per-individual hematocrit, sex-specific
#'
#' popgen does not generate hematocrit (see the file header), and
#' Extended_Model.r itself uses a single fixed Htc = 0.42 for every
#' individual. Real adult hematocrit is both sex-differentiated (testosterone
#' drives higher erythropoietin/red-cell mass in men; menstrual blood loss
#' lowers it in women) and has real inter-individual spread even within one
#' sex -- clinical reference intervals (~95% ranges) are approximately
#' 41-51% for men and 36-46% for women. `.HTC_REF` backs those out to a
#' mean/sd per sex (interval width / 1.96), and each individual draws its
#' own Htc from a normal distribution truncated to `lower`/`upper` (using
#' popgen_port.R's own .pg_truncated_norm_rnd(), the same truncation method
#' popgen uses for its own bounded draws) so sampling can never produce a
#' physiologically impossible hematocrit.
#'
#' @keywords internal
#'
.HTC_REF <- list(Male = c(mean = 0.46, sd = 0.025), Female = c(mean = 0.41, sd = 0.025))

.sample_Htc <- function(sex, lower = 0.20, upper = 0.60) {
  p <- .HTC_REF[[sex]]
  .pg_truncated_norm_rnd(p[["mean"]], p[["sd"]], lower, upper)
}

#=========================
# 5. Parameters of the model, for one popgen individual
#=========================
#' Build Extended_Model.r-compatible params for one popgen individual
#'
#' Same chemical-specific PK parameters, partition coefficients, rate
#' constants and dosing fields as Extended_Model.r's .create.params(); the
#' only difference is that BW and every V*/Q* come from `ind` (one row of a
#' popgen population) via .map_popgen_individual(), instead of from fixed
#' literature V*C/Q*C fractions of a user-supplied BW.
#'
#' @param user_input List with the same chemical/dosing fields .create.params()
#'   expects (chemical, admin_type, admin_dose, admin_time, ingestion,
#'   ingestion_time, exp_type, duration, and optionally time_scale). BW is
#'   NOT read from user_input here -- it comes from `ind`.
#' @param ind One row of the data.frame returned by .generate_population()$pop.
#' @param chem list(variables, PC) from .get_chemical_vars(user_input$chemical).
#' @export
#'
.create.params.population <- function(user_input, ind, chem) {
  with(as.list(user_input), {

    variables <- chem$variables
    PC <- chem$PC

    if (missing(time_scale) || is.na(time_scale)) {
      time_scale <- 1/24
    } else if (time_scale == "minutes") {
      time_scale <- 60
    } else if (time_scale == "hours") {
      time_scale <- 1
    } else if (time_scale == "days") {
      time_scale <- 1/24
    } else if (time_scale == "weeks") {
      time_scale <- (1/24)/7
    } else if (time_scale == "months") {
      time_scale <- ((1/24)/30)
    } else if (time_scale == "years") {
      time_scale <- ((1/24)/365)
    }
    inv_time_scale <- 1/time_scale

    # --- Chemical Specific Parameters (identical to Extended_Model.r) ---
    MW <- variables["MW",]
    Free <- variables["Free",]

    Vmax_baso_invitro <- variables["Vmax_baso_invitro", ]
    Km_baso <- variables["Km_baso", ] * variables["MW", ]
    Vmax_apical_invitro <- variables["Vmax_apical_invitro", ]
    Km_apical <- variables["Km_apical", ] * variables["MW", ]
    RAFbaso <- variables["RAFbaso", ]
    RAFapi <- variables["RAFapi", ]
    protein <- 2.0e-6
    GFRC <- 24.19 * inv_time_scale

    Htc <- .sample_Htc(ind[["sex"]])  # random per individual, sex-specific; popgen does not generate Htc (see .sample_Htc())

    # --- Partition Coefficients (Allendorf 2021); chemical-tissue property,
    # independent of popgen -- only organ VOLUME/FLOW is mapped from the
    # virtual population, not the chemical's partitioning behavior ---
    PR <- 0.1  # rest of body: (now applies to the popgen Bone compartment)
    PAdi <- (1 - Htc) * PC["Adipose", ]
    PBra <- (1 - Htc) * PC["Brain", ]
    PGon <- (1 - Htc) * PC["Gonads", ]
    PGI  <- (1 - Htc) * PC["Gut", ]
    PHea <- (1 - Htc) * PC["Heart", ]
    PL   <- (1 - Htc) * PC["Liver", ]
    PLun <- (1 - Htc) * PC["Lung", ]
    PMus <- (1 - Htc) * PC["Muscle", ]
    PSki <- (1 - Htc) * PC["Skin", ]
    PSpl <- (1 - Htc) * PC["Spleen", ]
    PPan <- (PGI + PSpl) / 2

    # --- Rate Constants (identical to Extended_Model.r) ---
    kdif <- 0.001 * inv_time_scale
    kabsc <- 2.12 * inv_time_scale
    kunabsc <- 7.06e-5 * inv_time_scale
    keffluxc <- variables["keffluxc", ] * inv_time_scale /24
    kbilec <- variables["kbilec", ] * inv_time_scale /24
    kurinec <- 0.063 * inv_time_scale
    water_consumption <- 1.36

    VplasC <- 0.0428  # fraction vol. of plasma (L/kg BW); not generated by popgen
    VfilC <- 4e-4      # fraction vol. of filtrate (L/kg BW); not generated by popgen
    VPTCC <- 1.35e-4   # vol. of proximal tubule cells (L/g kidney)

    # === Individual physiology from popgen ===
    phys <- .map_popgen_individual(ind, Htc, inv_time_scale)
    BW <- phys$BW
    QC <- phys$QC; QK <- phys$QK; QL <- phys$QL; QR <- phys$QR
    QAdi <- phys$QAdi; QBra <- phys$QBra; QGon <- phys$QGon; QHea <- phys$QHea
    QLun <- phys$QLun; QMus <- phys$QMus; QSki <- phys$QSki; QSpl <- phys$QSpl
    QPan <- phys$QPan; QGI <- phys$QGI
    VAdi <- phys$VAdi; VBra <- phys$VBra; VGon <- phys$VGon; VHea <- phys$VHea
    VLun <- phys$VLun; VMus <- phys$VMus; VSki <- phys$VSki; VSpl <- phys$VSpl
    VPan <- phys$VPan; VGI <- phys$VGI; VL <- phys$VL; VK <- phys$VK; VR <- phys$VR

    VPlas <- VplasC * BW
    Vfil <- VfilC * BW
    ML <- phys$MLiv * 1000   # mass of the liver (g); popgen mass directly, not re-derived from VL
    MK <- phys$MKid * 1000   # mass of the kidney (g); popgen mass directly, not re-derived from VK
    VKb <- VK * 0.16         # volume of blood in the kidney (L); Brown 1997
    VPTC <- MK * VPTCC       # VPTCC is L per GRAM of kidney MASS, so this must use MK (mass), not VK*1000 (which was only ~= kidney mass under the old density-1 assumption)
    MPTC <- VPTC * 1000

    PTC <- (VK / BW) * 1000 * 6e7  # number of PTC (cells/kg BW); Extended_Model.r derives this from the SAME
    # literature fraction (VKC) that also defines VK there, so the two stay self-consistent by construction.
    # Here VK is popgen's real per-individual kidney volume, not a fixed Brown 1997 population-average
    # fraction of BW -- using this individual's own VK/BW ratio (instead of a separate fixed VKC_lit
    # constant) keeps that same self-consistency instead of mixing a population-average kidney fraction
    # with this individual's own popgen-derived kidney volume everywhere else.

    Vmax_basoC <- (Vmax_baso_invitro * RAFbaso * PTC * protein * 60 * (MW / 1e12) * 1e6)  * inv_time_scale
    Vmax_apicalC <- (Vmax_apical_invitro * RAFapi * PTC * protein * 60 * (MW / 1e12) * 1e6)  * inv_time_scale
    Vmax_baso <- Vmax_basoC * BW^0.75
    Vmax_apical <- Vmax_apicalC * BW^0.75
    kbile <- kbilec * BW^(-0.25)
    kurine <- kurinec * BW^(-0.25)
    kefflux <- keffluxc * BW^(-0.25)
    GFR <- GFRC * VK * .gfr_age_factor(ind[["age"]], ind[["sex"]])
    kabs <- kabsc * BW^(-0.25)
    kunabs <- kunabsc * BW^(-0.25)


    return(list(
      "BW" = BW, 
      "Free" = Free, "QC" = QC, "QK" = QK, "QL" = QL, "QR" = QR,
      "QAdi" = QAdi, "QBra" = QBra, "QGon" = QGon, "QHea" = QHea,
      "QLun" = QLun, "QMus" = QMus, "QSki" = QSki, "QSpl" = QSpl,
      "QPan" = QPan, "QGI" = QGI,
      "VPlas" = VPlas, "VKb" = VKb, "Vfil" = Vfil, "VL" = VL,
      "VR" = VR, "ML" = ML,
      "VAdi" = VAdi, "VBra" = VBra, "VGon" = VGon, "VHea" = VHea,
      "VLun" = VLun, "VMus" = VMus, "VSki" = VSki, "VSpl" = VSpl, "VPan" = VPan,
      "VGI" = VGI, "MK" = MK,
      "VPTC" = VPTC, "Vmax_baso" = Vmax_baso, "Vmax_apical" = Vmax_apical,
      "kdif" = kdif, "Km_baso" = Km_baso, "Km_apical" = Km_apical,
      "kbile" = kbile, "kurine" = kurine, "kefflux" = kefflux,
      "GFR" = GFR, "kabs" = kabs, "kunabs" = kunabs,
      "PR" = PR, "PAdi" = PAdi, "PBra" = PBra, "PGon" = PGon, "PGI" = PGI,
      "PHea" = PHea, "PL" = PL, "PLun" = PLun, "PMus" = PMus, "PSki" = PSki,
      "PSpl" = PSpl, "PPan" = PPan, "water_consumption" = water_consumption,
      "admin_type" = admin_type, "admin_dose" = admin_dose,
      "admin_time" = admin_time, "ingestion" = ingestion,
      "ingestion_time" = ingestion_time, "duration" = duration,
      "time_scale" = time_scale, "exp_type" = exp_type
    ))

  })
}

#===============================================
# 6. Initial values for ODEs (identical to Extended_Model.r)
#===============================================
#'
#' @export
#'
.create.inits <- function(parameters){
  with( as.list(parameters),{
    "AR" = 0; "AAdi"=0; "ABra"=0; "AGon"=0;
    "AHea"=0; "ALun"=0; "AMus"=0; "ASki"=0; "ASpl"=0; "APan"=0;
    "Adif" = 0; "A_baso" = 0; "AKb" = 0;
    "ACl" = 0; "Aefflux" = 0;
    "A_apical" = 0; "APTC" = 0; "Afil" = 0;
    "Aurine" = 0; "ALumen" = 0; "AGI" = 0;
    "AabsLumen" = 0; "Afeces" = 0;
    "AL" = 0; "Abile" = 0; "Aplas_free" = 0;
    "ingestion" = 0;

    return(c("AR" = AR, "AAdi"=AAdi, "ABra"=ABra, "AGon"=AGon,
            "AHea"=AHea, "ALun"=ALun, "AMus"=AMus, "ASki"=ASki,
            "ASpl"=ASpl, "APan"=APan,
            "Adif" = Adif, "A_baso" = A_baso, "AKb" = AKb,
            "ACl" = ACl, "Aefflux" = Aefflux,
            "A_apical" = A_apical, "APTC" = APTC, "Afil" = Afil,
            "Aurine" = Aurine, "ALumen" = ALumen, "AGI" = AGI,
            "AabsLumen" = AabsLumen, "Afeces" = Afeces,
            "AL" = AL, "Abile" = Abile, "Aplas_free" = Aplas_free,
            "ingestion" = ingestion))
  })
}

#===================
# 7. Events function (identical to Extended_Model.r)
#===================
#'
#' @export
#'
.create.events <- function(parameters){
  with(as.list(parameters), {
    if (tolower(admin_type) == "iv") {
      ldose <- length(admin_dose)
      ltimes <- length(admin_time)
      if (ltimes != ldose) {
        stop("The times of administration should be equal in number to the doses")
      }
      events <- list(data = data.frame(
        var = Aplas_free, time = admin_time,
        value = admin_dose, method = "add"
      ))

    } else if (admin_type == "bolus") {
      ldose <- length(admin_dose)
      ltimes <- length(admin_time)
      if (ltimes != ldose) {
        stop("The times of administration should be equal in number to the doses")
      }
      events <- list(data = data.frame(
        var = "ALumen", time = admin_time,
        value = admin_dose, method = "add"
      ))
    } else if (admin_type == "oral") {
      lingest <- length(ingestion)
      lingesttimes <- length(ingestion_time)
      if (lingest != lingesttimes) {
        #stop("The times of ingestion rate change should be equal in vector of ingestion")
      }
      if(exp_type == "pharmacokinetics"){
          events <- list(data = data.frame(var = c("ALumen"),  time = ingestion_time,
                                           value = ingestion, method = c("add")))
        }else if(exp_type == "continuous"){
     events <- list(data = data.frame(var = c("ingestion"),  time = ingestion_time,
                                           value = ingestion, method = c("rep")))
        }else{
      stop("admin_type should be either 'iv', 'bolus', or 'oral'")
    }
      return(events)

  }}
  )
}

#==================
# 8. Custom functions (identical to Extended_Model.r)
#==================
#'
#' @export
#'
.custom.func <- function(){
  return()
}

#==============
# 9. ODEs System (identical to Extended_Model.r)
#==============
#'
#' @export
#'
.ode.func <- function(time, inits, params, custom.func) {
  with(as.list(c(inits, params)), {

    CR <- AR / VR
    CVR <- CR / PR
    

    CAdi <- AAdi / VAdi
    CVAdi <- CAdi / PAdi
   

    CBra <- ABra / VBra
    CVBra <- CBra / PBra
    

    CGon <- AGon / VGon
    CVGon <- CGon / PGon


    CHea <- AHea / VHea
    CVHea <- CHea / PHea


    CLun <- ALun / VLun
    CVLun <- CLun / PLun


    CMus <- AMus / VMus
    CVMus <- CMus / PMus


    CSki <- ASki / VSki
    CVSki <- CSki / PSki


    CSpl <- ASpl / VSpl
    CVSpl <- CSpl / PSpl

    Cpan <- APan / VPan
    CVPan <- Cpan / PPan

    CGI <- AGI / VGI
    CVGI <- CGI / PGI


    CKb <- AKb / VKb
    CVK <- CKb
    CPTC <- APTC / VPTC
    Cfil <- Afil / Vfil

    CL <- AL / VL
    CLiver <- AL / ML
    CVL <- CL / PL


    CA_free <- Aplas_free / VPlas
    CA <- CA_free / Free

    dAR <- QR * (CA - CVR) * Free

    dAAdi <- QAdi * (CA - CVAdi) * Free

    dABra <- QBra * (CA - CVBra) * Free

    dAGon <- QGon * (CA - CVGon) * Free

    dAHea <- QHea * (CA - CVHea) * Free

    dALun <- QLun * (CA - CVLun) * Free

    dAMus <- QMus * (CA - CVMus) * Free

    dASki <- QSki * (CA - CVSki) * Free

    dASpl <- QSpl * (CA - CVSpl) * Free

    dAPan <- QPan * (CA - CVPan) * Free

    dAdif <- kdif * (CKb - CPTC)
    dA_baso <- (Vmax_baso * CKb) / (Km_baso + CKb)
    dAKb <- QK * (CA - CVK) * Free - CA * GFR * Free - dAdif - dA_baso
    dACl <- CA * GFR * Free

    dAefflux <- kefflux * APTC
    dA_apical <- (Vmax_apical * Cfil) / (Km_apical + Cfil)
    dAPTC <- dAdif + dA_apical + dA_baso - dAefflux

    dAfil <- CA * GFR * Free - dA_apical - Afil * kurine

    dAurine <- kurine * Afil

    dALumen <- ingestion + - kabs * ALumen- kunabs * ALumen

    dAGI <- kabs * ALumen + QGI*(CA - CVGI) * Free
    dAabsLumen <- kabs * ALumen

    dAfeces <-  kunabs * ALumen + kbile * AL

    dAL <- QL * (CA - CVL) * Free - kbile * AL + QGI*(CVGI - CVL) * Free +
          QSpl*(CVSpl-CVL)*Free +QPan*(CVPan-CVL)*Free

    dAbile <- kbile * AL
    amount_per_gram_liver <- CLiver

    dAplas_free <- (QR * CVR * Free) + (QK * CVK * Free) + (QL * CVL * Free) +
    (QAdi*CVAdi*Free) + (QBra*CVBra*Free) + (QGon*CVGon*Free) + (QHea*CVHea*Free) +
    (QLun*CVLun*Free) +(QMus*CVMus*Free) +(QSki*CVSki*Free)+(QSpl*CVL*Free)+(QPan*CVL*Free)+
    (QGI*CVL*Free)- (QC * CA * Free) + dAefflux

    dingestion <- 0

    Atissue <- Aplas_free + AR + AAdi + ABra + AGon + AHea+ ALun +
    AMus + ASki + ASpl+ APan + AKb + Afil + ALumen+ AGI + APTC + AL
    Aloss <- Aurine + Afeces
    Atotal <- Atissue + Aloss

    list(c(
        "dAR" = dAR, "dAAdi" = dAAdi, "dABra" = dABra, "dAGon" = dAGon,
        "dAHea" = dAHea, "dALun" = dALun, "dAMus" = dAMus, "dASki" = dASki,
        "dASpl" = dASpl, "dAPan"=dAPan,
        "dAdif" = dAdif, "dA_baso" = dA_baso, "dAKb" = dAKb,
        "dACl" = dACl, "dAefflux" = dAefflux,
        "dA_apical" = dA_apical, "dAPTC" = dAPTC, "dAfil" = dAfil,
        "dAurine" = dAurine, "dALumen" = dALumen, "dAGI" = dAGI,
        "dAabsLumen" = dAabsLumen, "dAfeces" = dAfeces,
        "dAL" = dAL, "dAbile" = dAbile, "dAplas_free" = dAplas_free,
        "dingestion" = dingestion
      ),
      "amount_per_gram_liver" = amount_per_gram_liver,
      "Atissue" = Atissue, "Aloss" = Aloss, "Atotal" = Atotal,
      "CR" = CR, "CVR" = CVR,
      "CAdi"=CAdi, "CVAdi"=CVAdi,
      "CBra"=CBra, "CVBra"=CVBra,
      "CGon"=CGon, "CVGon"=CVGon,
      "CHea"=CHea, "CVHea"=CVHea, 
      "CLun"=CLun, "CVLun"=CVLun, 
      "CMus"=CMus, "CVMus"=CVMus, 
      "CSki"=CSki, "CVSki"=CVSki,
      "CSpl"=CSpl, "CVSpl"=CVSpl, 
      "Cpan"=Cpan, "CVPan"=CVPan, 
      "CKb" = CKb,  "CVK" = CVK, "CPTC" = CPTC,
      "Cfil" = Cfil,
      "CL" = CL, "CVL" = CVL, 
      "CGI" = CGI, "CVGI" = CVGI, 
      "CA_free" = CA_free, "CA" = CA)
})
}

#=========================
# 10. Population driver
#=========================
#' Run the extended PBK model across a popgen virtual population
#'
#' Generates a virtual population with .generate_population() and solves the
#' ODE system once per individual, using that individual's popgen-derived
#' organ mass/flow (Bone -> rest of body; see the file header for the full
#' mapping) via .create.params.population(). The administered dose and every
#' chemical-specific PK parameter are identical across individuals; only
#' physiology varies.
#'
#' @param user_input List combining:
#'   - the population-generation fields required by .generate_population()
#'     (n, dataset, age_range, bmi_range, height_range, prob_male,
#'     ethnicity_probs, population_type, optional seed), and
#'   - the same chemical/dosing fields Extended_Model.r's .create.params()
#'     expects (chemical, admin_type, admin_dose, admin_time, ingestion,
#'     ingestion_time, exp_type, duration, exposure_time, optional
#'     time_scale). BW is NOT supplied here -- popgen generates it per
#'     individual.
#' @param solver,rtol,atol passed through to deSolve::ode().
#' @return list(
#'   population = data.frame, one row per individual (popgen demographics,
#'     organ mass/flow, and the id used to join against `results`),
#'   results = data.frame stacking every individual's full ODE time-course,
#'     tagged by `id`
#' )
#' @export
#'
.run_population_extended <- function(user_input, solver = "lsodes", rtol = 1e-5, atol = 1e-5) {

  .check_required(user_input, c(.required_population_fields,
                                 "chemical", "admin_type", "exp_type", "duration", "exposure_time"))

  gen <- .generate_population(user_input)
  pop <- gen$pop
  message(sprintf("Generated %d individuals (%d discarded by popgen's rejection rules)",
                   nrow(pop), gen$n_discarded))

  chem <- .get_chemical_vars(user_input$chemical)

  results_list <- vector("list", nrow(pop))
  for (i in seq_len(nrow(pop))) {
    ind <- pop[i, ]
    params <- .create.params.population(user_input, ind, chem)
    inits <- .create.inits(params)
    events <- .create.events(params)

    sol <- as.data.frame(deSolve::ode(
      times = user_input$exposure_time, func = .ode.func, y = inits,
      parms = params, events = events, method = solver, rtol = rtol, atol = atol
    ))
    sol$id <- ind[["id"]]
    results_list[[i]] <- sol
  }

  results <- do.call(rbind, results_list)

  list(population = pop, results = results)
}

# --- Example usage ---------------------------------------------------------
user_input <- list(
  # popgen population-generation parameters (all required)
  n = 100, dataset = "ICRP", age_range = c(65, 70), bmi_range = c(20, 24),
  height_range = c(180, 190), prob_male = 1, ethnicity_probs = c(1, 0, 0),
  population_type = "Realistic", seed = 123,
  # chemical / dosing parameters (same as Extended_Model.r, minus BW)
  # admin_dose is non-zero and ingestion is 0, so this is a single oral bolus
  # dose -> admin_type must be "bolus" (routes admin_dose into ALumen via
  # .create.events()); admin_type "oral" would instead read the dose from
  # `ingestion`, which is 0 here, silently giving a zero dose.
  chemical = "PFOA", admin_type = "bolus", exp_type = "pharmacokinetics",
  ingestion = 0, ingestion_time = 0, admin_dose = 3.99, admin_time = 0,
  duration = 500, time_scale = "days",
  exposure_time = sort(unique(c(seq(0, 500, 1), 500)))
)
out <- .run_population_extended(user_input)
head(out$population)
head(out$results)

# --- Population percentile plot: 2.5th / 50th / 97.5th of plasma concentration (CA) ---
# CA (total plasma concentration, ug/L) is the headline PBK output; swap the
# "CA" column below for e.g. "CL" (liver) or "amount_per_gram_liver" to plot
# a different compartment the same way.
percentiles_CA <- out$results %>%
  group_by(time) %>%
  summarise(
    p2.5  = quantile(CA, probs = 0.025, na.rm = TRUE),
    p50   = quantile(CA, probs = 0.5,   na.rm = TRUE),
    p97.5 = quantile(CA, probs = 0.975, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  pivot_longer(cols = c(p2.5, p50, p97.5), names_to = "percentile", values_to = "CA") %>%
  mutate(percentile = factor(percentile, levels = c("p2.5", "p50", "p97.5"),
                              labels = c("2.5th percentile", "Median (50th)", "97.5th percentile")))

theme_percentile <- theme_classic() +
  theme(
    text = element_text(size = 14, family = "sans"),
    axis.title = element_text(size = 15, face = "bold"),
    axis.text = element_text(size = 12, color = "black"),
    axis.line = element_line(color = "black", linewidth = 0.6),
    axis.ticks = element_line(color = "black", linewidth = 0.5),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    legend.position = "top",
    plot.title = element_text(size = 16, face = "bold")
  )
plasma_exp <- read.csv("exp_data_plasma.csv") %>% select("time", "PFOA")

# Observed data is a separate layer with its own x/y/color mapping
# (inherit.aes = FALSE), since plasma_exp has no "percentile" column to
# satisfy the line layers' color/linetype/linewidth aesthetics.
obs_label <- "Observed (exp_data_plasma.csv)"

p_percentiles <- ggplot(percentiles_CA, aes(x = time, y = CA, color = percentile,
                                             linetype = percentile, linewidth = percentile)) +
  geom_line() +
  geom_point(data = plasma_exp, aes(x = time, y = PFOA, color = obs_label),
             inherit.aes = FALSE, shape = 21, fill = "white", size = 3, stroke = 1) +
  scale_color_manual(values = setNames(
    c("#6da7ec", "#2a78d6", "#6da7ec", "#0b0b0b"),
    c("2.5th percentile", "Median (50th)", "97.5th percentile", obs_label)
  )) +
  scale_linetype_manual(values = c("2.5th percentile" = "dashed",
                                    "Median (50th)" = "solid",
                                    "97.5th percentile" = "dashed")) +
  scale_linewidth_manual(values = c("2.5th percentile" = 0.7,
                                     "Median (50th)" = 1.1,
                                     "97.5th percentile" = 0.7)) +
  # color has a 4th level ("Observed") that linetype/linewidth don't, so
  # ggplot can't auto-merge the three legends -- merge them manually into a
  # single legend keyed on color, with per-entry line/point styling.
  guides(
    linetype = "none",
    linewidth = "none",
    color = guide_legend(
      title = NULL,
      override.aes = list(
        linetype = c("dashed", "solid", "dashed", "blank"),
        linewidth = c(0.7, 1.1, 0.7, NA),
        shape = c(NA, NA, NA, 21),
        fill = c(NA, NA, NA, "white")
      )
    )
  ) +
  labs(
    x = paste0("Time (", user_input$time_scale, ")"),
    y = "Plasma concentration, CA (µg/L)",
    title = paste0("Population PBK simulation — ", user_input$chemical,
                    " (n = ", nrow(out$population), ")")
  ) +
  theme_percentile

print(p_percentiles)

ggsave("population_percentiles_CA.png", p_percentiles, width = 8, height = 6, dpi = 300)
