# =============================================================================
#  Forward_Dosimetry_Stochastic.r
#  Stochastic (population) counterpart to shiny_app/R/forward_dosimetry.r.
#
#  forward_dosimetry_stochastic() below takes the SAME dosing/exposure
#  arguments, but replaces the single fixed BW with a popgen virtual
#  population -- the same population-generation inputs
#  Extended_Model_Population.r's .generate_population() requires (n,
#  dataset, age_range, bmi_range, height_range, prob_male, ethnicity_probs,
#  population_type, optional seed). Physiology (organ mass/flow,
#  sex-specific hematocrit, age-corrected GFR) comes from
#  Extended_Model_Population.r exactly as its own .run_population_extended()
#  already produces it; the one thing that function does NOT do --
#  converting a per-kg-BW ingestion rate to an absolute amount using BW
#  (forward_dosimetry()'s `ingestion * BW / 1000`, done once there because
#  there is only one BW) -- is done per individual here instead, since every
#  virtual individual has a different popgen-derived body weight.
#
#  Dosing note: Extended_Model_Population.r's .create.events() no longer has
#  a separate admin_type ("bolus"/"oral") switch -- dosing is driven purely
#  by `exp_type`: "pharmacokinetics" adds `ingestion` (dose amount(s)) to the
#  stomach lumen at `ingestion_time`; "continuous" treats `ingestion` as a
#  repeating intake RATE instead. There is no more admin_dose/admin_time/
#  admin_type at all -- every dose, one-off or continuous, goes through
#  `ingestion`/`ingestion_time`, and .ingestion_for_BW() below BW-scales it
#  per individual either way.
#
#  Dependencies: Extended_Model_Population.r (and, transitively,
#  popgen_consts.R / popgen_port.R, estimated_parameters.csv) must be in the
#  working directory.
# =============================================================================

library(deSolve)
library(tidyverse)

#=========================
# 0. Load Extended_Model_Population.r's function definitions
#=========================
# Source everything up to (not including) its own "# --- Example usage"
# block, so we reuse .get_chemical_vars()/.generate_population()/
# .map_popgen_individual()/.gfr_age_factor()/.sample_Htc()/
# .create.params.population()/.create.inits()/.create.events()/.ode.func()/
# .check_required() without re-running its own 100-individual demo
# simulation as a side effect of loading this file.
if (!exists(".create.params.population")) {
  if (!file.exists("Extended_Model_Population.r"))
    stop("Forward_Dosimetry_Stochastic.r requires Extended_Model_Population.r in the working directory")
  .fds_lines <- readLines("Extended_Model_Population.r")
  .fds_cut <- grep("^# --- Example usage", .fds_lines)[1]
  if (is.na(.fds_cut))
    stop("Could not find the '# --- Example usage' marker in Extended_Model_Population.r -- has the file structure changed?")
  .fds_tmp <- tempfile(fileext = ".R")
  writeLines(.fds_lines[seq_len(.fds_cut - 1)], .fds_tmp)
  source(.fds_tmp)
  rm(.fds_lines, .fds_cut, .fds_tmp)
}

#=========================
# 1. Stochastic forward dosimetry
#=========================
#' Population counterpart to shiny_app/R/forward_dosimetry.r's forward_dosimetry()
#'
#' Same dosing/exposure arguments as forward_dosimetry() (chemical, ingestion,
#' ingestion_time, exp_type, time_scale, duration, time_step) -- except there
#' is no single BW argument, and no admin_dose/admin_time/admin_type (see the
#' file header: Extended_Model_Population.r's .create.events() dropped that
#' switch, so every dose -- one-off or continuous -- goes through `ingestion`/
#' `ingestion_time`, selected by `exp_type`). Instead of BW, `n` virtual
#' individuals are generated by popgen (age_range/bmi_range/height_range/
#' prob_male/ethnicity_probs/dataset/population_type, exactly as
#' .generate_population() requires), and the ODE system is solved once per
#' individual using THEIR OWN popgen-derived body weight and physiology.
#'
#' `ingestion` is interpreted the same way forward_dosimetry() interprets it:
#' a per-kg-BW daily rate (e.g. ug/kg/day) -- whether it is applied as a
#' one-off dose (`exp_type = "pharmacokinetics"`) or a continuous intake rate
#' (`exp_type = "continuous"`) is .create.events()'s decision, not this
#' function's. forward_dosimetry() converts that per-kg-BW rate to an
#' absolute amount using its single BW once (`ingestion * BW / 1000`,
#' time_scale-rescaled); here the identical conversion is applied per
#' individual instead, since every individual has a different BW.
#'
#' @param n,dataset,age_range,bmi_range,height_range,prob_male,ethnicity_probs,
#'   population_type,seed Population-generation inputs, passed straight to
#'   .generate_population() (see Extended_Model_Population.r for the exact
#'   meaning of each).
#' @param duration,time_step,chemical,ingestion,ingestion_time,exp_type,
#'   time_scale Dosing/exposure inputs, same names and meaning as
#'   forward_dosimetry()'s (minus admin_dose/admin_time/admin_type, which no
#'   longer exist -- see the file header).
#' @param solver,rtol,atol Passed through to deSolve::ode().
#' @return list(
#'   population = data.frame, one row per individual (popgen demographics,
#'     organ mass/flow, and the id used to join against `results`),
#'   results = data.frame stacking every individual's full ODE time-course,
#'     tagged by `id` -- same shape .run_population_extended() returns.
#' )
#' @export
#'
forward_dosimetry_stochastic <- function(n, dataset, age_range, bmi_range, height_range,
                                          prob_male, ethnicity_probs, population_type, seed = NULL,
                                          duration, time_step, chemical, ingestion, ingestion_time,
                                          exp_type, time_scale,
                                          solver = "lsodes", rtol = 1e-5, atol = 1e-5) {

  exposure_time <- sort(unique(c(seq(0, duration, by = time_step), duration)))

  user_input <- list(
    n = n, dataset = dataset, age_range = age_range, bmi_range = bmi_range,
    height_range = height_range, prob_male = prob_male, ethnicity_probs = ethnicity_probs,
    population_type = population_type, seed = seed,
    chemical = chemical,
    ingestion_time = ingestion_time, exp_type = exp_type, duration = duration,
    time_scale = time_scale, exposure_time = exposure_time
  )

  .check_required(user_input, c(.required_population_fields,
                                 "chemical", "exp_type", "duration", "exposure_time"))

  gen <- .generate_population(user_input)
  pop <- gen$pop
  message(sprintf("Generated %d individuals (%d discarded by popgen's rejection rules)",
                   nrow(pop), gen$n_discarded))

  chem <- .get_chemical_vars(chemical)

  # forward_dosimetry()'s per-kg-BW -> absolute-amount conversion, unchanged
  # formula, applied per individual since each has a different popgen BW
  .ingestion_for_BW <-  function(BW) {
    if (identical(exp_type, "pharmacokinetics")) return(ingestion * BW / 1000)
    switch(time_scale,
      "minutes" = (1/24/60) * ingestion * BW / 1000,
      "hours"   = (1/24)    * ingestion * BW / 1000,
      "days"    =             ingestion * BW / 1000,
      "weeks"   = 7         * ingestion * BW / 1000,
      "months"  = 30        * ingestion * BW / 1000,
      "years"   = 365       * ingestion * BW / 1000
    )
  }

  results_list <- vector("list", nrow(pop))
  for (i in seq_len(nrow(pop))) {
    ind <- pop[i, ]

    ind_user_input <- user_input
    ind_user_input$ingestion <- .ingestion_for_BW(ind[["body_mass_kg"]])

    params <- .create.params.population(ind_user_input, ind, chem)
    inits <- .create.inits(params)
    events <- .create.events(params)

    sol <- as.data.frame(deSolve::ode(
      times = exposure_time, func = .ode.func, y = inits,
      parms = params, events = events, method = solver, rtol = rtol, atol = atol
    ))
    sol$id <- ind[["id"]]
    results_list[[i]] <- sol
  }

  results <- do.call(rbind, results_list)

  list(population = pop, results = results)
}

